### ISSUE TITLE
Warning with Cake 0.33.0

### ISSUE THREAD

**Issue by zplan** [cake-contrib/Cake.Incubator#101]
When using cake 0.33.0 and cake.incubator 4.0.2 I get always a warning at startup:

Preparing to run build script...
Running build script...
**Namespace Cake.Incubator.EnvironmentExtensions excluded by code generation, affected methods:
        method "EnvironmentVariable" excluded from code generation and will need to be fully qualified on ICakeContext.**

Addin definition in .cake file:
#addin nuget:?package=Cake.Incubator&version=4.0.2

packages.config:
```xml
<package id="Cake" version="0.33.0" />
```

**Comment by wwwlicious** [comment]
@zplan  This behaviour was introduced by the cake team in [Cake-2487](https://github.com/cake-build/cake/issues/2487) and is intentional. The alias in that namespace has been added to the core cake library so to avoid method signature clashes, it excludes that specific addin namespace. It is safe to ignore.
