### ISSUE TITLE
Old Cake.Core version

### ISSUE THREAD

**Issue by kimbell** [cake-contrib/Cake.Incubator#67]
When running a build today, I received the following error: 

Error: The assembly 'Cake.Incubator, Version=1.7.2.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
PS C:\Norwegian\Repos\csc\services.checkin>

My quick fix was to disable verification, but the reference should be updated.

**Comment by gep13** [comment]
@kimbell this warning is by design, meaning that we want to ensure compatibility between Cake versions when we know that there have been breaking changes.

The fact that you are seeing this error suggests that you haven't pinned to a specific version of Cake, which is something that we strongly recommend.  Have a look here:

https://cakebuild.net/docs/tutorials/pinning-cake-version

And watch the video for more information.

**Comment by warrenrumak** [comment]
So the implication is that we should expect Incubator compatibility to lag behind Cake releases?  If so, the README.md file should be clearer that these sudden incompatibilities are possible and that users should pin Cake versions to avoid this issue.

**Comment by gep13** [comment]
@warrenrumak we go out of our way to tell people to pin their Cake version.  You can see that in the very first Getting Started article here:

https://cakebuild.net/docs/tutorials/getting-started

We have an entire tutorial dedicated to it here:

https://cakebuild.net/docs/tutorials/pinning-cake-version

And prior to every release we remind people on both Gitter channels that the release is pending, and that they should pin there Cake version.

Is there other things that you think we should be doing?  If so, please feel free to make PR's to improve the situation.

**Comment by kimbell** [comment]
Most packages on Nuget follow Semantic versioning; so that is what people expect. Going from 0.22.0 to 0.26.0 indicates that backward compatible features have been added. If the version changed from 0.22.0 to 1.0.0, it would be a different story. 

Since the cake system has this custom version check, is it feasible to have it only trigger on major versions?

**Comment by gep13** [comment]
@kimbell Cake is following semantic versioning.  The distinction here is that we haven't reached our first public API version, 1.0.0.  As a result, there are, and still will be, breaking changes, until we release that first 1.0.0 version.  This is very standard for applications which are following semantic versioning.  Once we ship 1.0.0, all breaking changes will be a major release, but for now, that is not the case.

Again, this is one of the many reasons why we recommend that you pin to a specific Cake version, as well as all of the tools and addins that you are using.  This is what will give you the most reliable, repeatable and maintainable builds.

> Going from 0.22.0 to 0.26.0 indicates that backward compatible features have been added.

This is simply not true.  This would be true if we had went from 1.22.0 to 1.26.0, but not before our 1.0.0 release.

**Comment by ckolumbus** [comment]
@gep13 can we expect an updated version of the Incubator if we need to switch to the new cake version 0.26.0 and also need the Incubator functionality (namely "CustomProjectParserResult")
Thanks for all the work!

**Comment by warrenrumak** [comment]
@gep13 Doesn't really help people who are new to cake and trying to have a good first experience.  They'll install Cake 0.26, have a good experience, then install Incubator and have a bad experience and won't understand.

If the Incubator project isn't going to stay in sync with Cake on a timely basis, and if Cake isn't going to commit to 1.0 in the foreseeable future, then you should do a better job of informing people using Incubator that things will arbitrarily break on arbitrary point upgrades.

Always keep the first-time user's experience in mind.

**Comment by ckolumbus** [comment]
@warrenrumak @gep13 as one of those users i see the whole dependency management a little problematic, not only 'Incubator', I have 15 dependencies now in my project and needed (as I should) pin down all versions. But finding out whether there is an update and how to integrate it is a quiet a bit of a hassle. Maybe if we can address this in general, pinning versions down and having a easy/ier update process would help the overall experience.
Is there a state-of-the-art process on how to find out and eventually upgrade certain versions/dependencies?

**Comment by gep13** [comment]
>@warrenrumak said...
If the Incubator project isn't going to stay in sync with Cake on a timely basis

Just so we are clear...  What do you regard as a timely basis?  Bearing in mind that Cake, and it's Community, are a team of volunteers, working in their spare time on a project that interests them.  Many of these contributors, myself included have young families.

>@warrenrumak said...
and if Cake isn't going to commit to 1.0 in the foreseeable future,

This is something that we would like to get to, but there are no immediate plans to jump to this yet.

>@warrenrumak said...
then you should do a better job of informing people using Incubator that things will arbitrarily break on arbitrary point upgrades.

Do you have any suggestions as to how we do this?  Our guidance is VERY clear, in that we recommend pinning to a specific version of Cake, as well as pinning to all version of tools/addins/modules that you could be using.

>@warrenrumak...
Always keep the first-time user's experience in mind.

This is a valid point.  The one thing that I will say is that we try VERY hard not to cause breaking changes in Cake.  In 87 releases of Cake, we have only introduced breaking changes 5 times.  And normally, as in the case of 0.26.0, it is due to upstream changes that we have felt that require to be pulled in, i.e. support for .NET Core 2.0.

>@kimbell said...
But finding out whether there is an update and how to integrate it is a quiet a bit of a hassle. Maybe if we can address this in general, pinning versions down and having a easy/ier update process would help the overall experience.

We are open to suggestions as to how this can be improved.  All the addin's that live under the Cake-Contrib Organsation announce their new releases to both Gitter and Twitter.  These are reasonably low traffic accounts, which you could subscribe to for updates on addins that you might be interested in.

https://gitter.im/cake-contrib/Lobby
https://twitter.com/cakecontrib

>@kimbell said...
Is there a state-of-the-art process on how to find out and eventually upgrade certain versions/dependencies?

No, I don't think we have what you are looking for.

**Comment by ckolumbus** [comment]
@gep13 regarding the update/upgrade process improvement: I saw a project [cup](https://github.com/cake-contrib/Cup) cake (nice pun :+1: ) which seems to address the update issue. Anyone here who is involved in that project? Unfortunately there is no Readme or anything so providing support is difficult (at the moment).

**Comment by ckolumbus** [comment]
@gep13 ... and i forgot regarding the releases: I did not know about the {G,Tw}itter accounts. Thanks for pointing this out!

**Comment by gep13** [comment]
@ckolumbus that project is a work in progress.  @patriksvensson is the person that has been working on it.  I am not sure what state that is in though.  There is another project in the works as well by @Jericho which aims to allow an "audit" of all addins, to see what there current state is, so that will help identify which addin's need to be updated.  That project is here:

https://github.com/cake-contrib/Cake.AddinDiscoverer

**Comment by jessejacob** [comment]
Same error as originally reported today still showing up for 2.0.0, so it looks like the fix was ineffective...am I doing something wrong?

Error: The assembly 'Cake.Incubator, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

**Comment by patriksvensson** [comment]
@jessejacob You're right.

![image](https://user-images.githubusercontent.com/357872/37587802-93523ad8-2b60-11e8-8308-5e0b4300823d.png)

@wwwlicious Looks like you should drop net45/net46 here.

**Comment by Jericho** [comment]
@patriksvensson I agree that addins no longer need to multi-target and targeting netstandard2.0 is sufficient for cake 0.26.0. However, cake should be able to pick the most appropriate target but, unfortunately, it doesn’t. I reported this [issue](https://github.com/cake-build/cake/issues/2084).

**Comment by patriksvensson** [comment]
@Jericho I don't think Cake has any saying in what tfm that is chosen. I think that is the NuGet client library. Correct me if I'm wrong @mholo65.

**Comment by mholo65** [comment]
Yep, NuGet will pick `netxx` TFM over `netstandardxx`if we are running on full framework. Why is the `net46` version targeting 0.22.0 version of Cake.Core?

**Comment by mholo65** [comment]
We need to resolve the correct binaries to load, [here](https://github.com/cake-build/cake/blob/develop/src/Cake.NuGet/NuGetContentResolver.cs#L93) we use NuGet.Client libraries to get the best match.

**Comment by Jericho** [comment]
This “reducer” uses nuget to figure out the “nearest” target? Interesting...

**Comment by pascalberger** [comment]
@mholo65 I this this was done like this to support multiple Cake versions in parallel, as the recent API breaking changes also came with a change in the target Framework. This worked for change from net45 to net46, but doesn't resolve now as it seems with netstandard2.0

**Comment by mholo65** [comment]
@jericho, yes it’s the same stuff used in VS tooling, msbuild, etc...

@pascalberger yes, that worked because `net46` is more suitable for `net461` than `net45`. However, `net46` is still more suitable than `netstandard2.0` for `net461`.

**Comment by wwwlicious** [comment]
I have removed the net45 and net46 targets and will shortly publish version 2.0.1. Hopefully this will resolve the issue.
